#! /usr/bin/perl

#  Creates the fontdata.js file from the individual font data files
#  
#  Usage:  ./makeData

require "config-files.pl";

foreach $file (@files) {
  (my $name = $file) =~ s{\.[^.]+$}{};
  $file =~ s/STIX_//;
  $file .= "-Regular" unless $file =~ m/-/;
  $file =~ s!-!/!g;
  $file = "fonts/STIX-Web/$file"; 
  $file .= (-e "$file/Main.js" ? "/Main.js" : "/All.js");
  open(FONT,$file) || print "Can't open $file\n";
  $lines = join("",<FONT>);
  close(FONT);
  $lines =~ s/.*FONTDATA/HTMLCSS.FONTDATA/s;
  $lines =~ s/};.*/};\n/s;
  print "Generating $name.js...\n";
  open(DATA,">data/$name.js");
  print DATA $lines;
  close(DATA);
}
