#! /bin/csh -f

#
#  Runs fontforge to create all the MathJax font files
#  (in the OTF and TTF formats)
#  
#  Usage: ./makeOTF
#

echo "MathJax_Size4.ff"
fontforge -lang=ff -script ff/MathJax_Size4.ff

foreach file (ff/*.ff)
echo ""
echo $file:t
fontforge -lang=ff -script $file
end
