#! /bin/bash

source ../../../custom.cfg

for file in `ls otf/*.otf | $SED 's|otf/\(.*\)\.otf|\1|'`; do
echo "Generating $file.woff..."
$SFNT2WOFF otf/$file.otf
done
mv otf/*.woff woff

rm woff/*WinChrom* woff/*WinIE6* woff/*Greek*

