#! /bin/bash

#
#  Make the fonts in all the formats
#
#    Usage:  ./makeFonts
#

echo "OTF and TTF"
./makeOTF

echo ""
echo "EOT"
./makeEOT

echo ""
echo "SVG"
./makeSVG

echo ""
echo "WOFF"
./makeWOFF

#echo ""
#echo "CSS"
#./makeCSS

rm otf/*Greek*
rm ttf/*WinChrom* ttf/*WinIE6*

