#! /bin/bash

#
#  Make the SVG fonts from the TTF fonts
#    (requires the batik library)
#
#    Usage: ./makeSVG
#

source ../../../custom.cfg

for file in `ls ttf/*.ttf | $SED 's|ttf/\(.*\)\.ttf|\1|'`; do
echo "Generating $file.svg..."
$JAVA -jar $TTF2SVG ttf/$file.ttf -id $file -o svg/$file.svg -l 0 -h 65535
done

rm svg/*WinIE6* svg/*Greek*
