#! /bin/bash

#
#  Runs fontforge to create all the MathJax font files
#  (in the OTF and TTF formats)
#  
#  Usage: ./makeOTF
#

source ../../../custom.cfg

echo "MathJax_Size4.ff"
$FONTFORGE -lang=ff -script ff/MathJax_Size4.ff

for file in `cd ff; ls *.ff`; do
echo ""
echo $file
$FONTFORGE -lang=ff -script ff/$file
done
