#! /bin/csh -f

#
#  Make the SVG fonts from the TTF fonts
#    (requires the batik library)
#
#    Usage: ./makeSVG
#

foreach file (ttf/*.ttf)
echo $file:t:r
java -jar lib/batik-1.7/batik-ttf2svg.jar $file -id $file:t:r -o svg/$file:t:r.svg -l 0 -h 65535
end

rm svg/*WinIE6* svg/*Greek*
