#! /bin/bash

#
#  Make the EOT fonts from the TTF fonts
#
#    Usage:  ./makeEOT
#

source ../../../custom.cfg

for file in `ls ttf/*.ttf | $SED 's|ttf/\(.*\)\.ttf|\1|'`; do
echo "Generating $file.eot..."
$TTF2EOT < ttf/$file.ttf > eot/$file.eot
done

rm eot/*WinChrome* eot/*Greek*
