#! /bin/bash

#  Put the font files into the proper locations
#  
#  Usage: ./makeInstall

source ../../../custom.cfg

#
#  Copy the font files into the system font directory
#
#rm $FONTDIR/MathJax_*
cp otf/*.otf $FONTDIR
cp ttf/*Greek*.ttf $FONTDIR

#
#  Put the fonts into the MathJax fonts folder
#  
rm ../../../../mathjax/fonts/HTML-CSS/TeX/otf/*.*
rm ../../../../mathjax/fonts/HTML-CSS/TeX/eot/*.*
rm ../../../../mathjax/fonts/HTML-CSS/TeX/svg/*.*
rm ../../../../mathjax/fonts/HTML-CSS/TeX/woff/*.*
#rm ../../../../mathjax/fonts/HTML-CSS/TeX/css/*.*
cp otf/*.otf ../../../../mathjax/fonts/HTML-CSS/TeX/otf
cp eot/*.eot ../../../../mathjax/fonts/HTML-CSS/TeX/eot
cp svg/*.svg ../../../../mathjax/fonts/HTML-CSS/TeX/svg
cp woff/*.woff ../../../../mathjax/fonts/HTML-CSS/TeX/woff
#cp css/*.css ../../../../mathjax/fonts/HTML-CSS/TeX/css

