#! /usr/bin/perl

#
#  Compresses scripts in the MathJax project
#
#  Usage:  packMJ [--force] [project-dir]

use Cwd;
use FindBin;

if ($ARGV[0] eq '--force') {$force = true; shift}

$DST = shift || getcwd;
$SRC = "$DST/unpacked";
$bindir = $FindBin::Bin;
$PACKMJFILE = "$bindir/packMJfile";

sub packDir {
  my ($src,$dst) = @_;
  opendir(SRC,$src);
  my @files = grep(/^[^.]/,readdir(SRC));
  closedir(SRC);
  foreach my $file (@files) {
    if (-d "$src/$file") {
      next if "$src/$file" eq "$SRC/fonts";
      next if "$src/$file" eq "$SRC/docs";
      next if "$src/$file" eq "$SRC/unpacked";
      if (! -e "$dst/$file") {mkdir "$dst/$file"}
      packDir("$src/$file","$dst/$file");
    } elsif ($file =~ m/\.js$/) {
      packFile($src,$dst,$file);
    }
  }
}

sub packFile {
  my ($src,$dst,$file) = @_;
  $src .= "/$file"; $dst .= "/$file";
  my ($stime,$ssize) = (stat($src))[9,7];
  my $dtime = (stat($dst))[9];
  return if $stime <= $dtime && !$force;
  system("$PACKMJFILE '$src' '$dst'");
  my $dsize = (stat($dst))[7];
  print "Size: $dsize,  Original: $ssize [saved: ",$ssize-$dsize," or ",
    sprintf("%.1f",100*($ssize-$dsize)/$ssize),"%]\n";
}

packDir($SRC,$DST);

1;
