#! /usr/local/bin/perl

#  Compresses a MathJax file and reports the new size and savings.
#  You need to have yuicompressor in order for this to work
#  
#  Usage:  packMJfile src-file dest-file

use Cwd;
use FindBin;

$bindir = $FindBin::Bin;
$YUI = "$bindir/yuicompressor-2.4.2/build/yuicompressor-2.4.2.jar";
$YUIFILTER = "$bindir/yuiFilter";
$src = shift; $dst = shift;


if ($src =~ m!/config/(local/local|MathJax)\.js$!) {
  print "============================================\n";
  print "Copying: $src\n";
  system("cp '$src' '$dst'");
  exit;
}

print "============================================\n";
print "Compressing: $src\n";
print "--------------------------------------------\n";
system("java -jar '$YUI' -v -o '$dst' '$src' 2>&1 | $YUIFILTER");

open(MJX,"<", $dst);
@lines = <MJX>;
close(MJX);
$compressed = join("",@lines);

$template = "$bindir/template.js";
$template = "$bindir/template-MathJax.js" if $dst =~ m!(^|/)MathJax\.js$!;

open(MJX,"<",$template);
@lines = <MJX>;
close(MJX);
$lines = join("",@lines);

$dstname = $dst; $dstname =~ s!.*/MathJax!/MathJax!;
$lines =~ s/%%%NAME%%%/$dstname/;
$lines =~ s/%%%DATA%%%/$compressed/;


open(MJX,">",$dst);
print MJX $lines;
close(MJX);

1;

