#! /usr/bin/perl

#  Compresses a MathJax file and reports the new size and savings.
#  You need to have yuicompressor in order for this to work
#  
#  Usage:  packMJfile src-file dest-file

require "../custom.cfg.pl";

use Cwd;
use FindBin;

$bindir = $FindBin::Bin;
$YUIFILTER = "$bindir/yuiFilter";
$src = shift; $dst = shift;


if ($src =~ m!/config/(local/local|default)\.js$!) {
  print "============================================\n";
  print "Copying: $src\n";
  system("cp '$src' '$dst'");
  exit;
}

print "============================================\n";
print "Compressing: $src\n";
print "--------------------------------------------";
system("java -jar '$YUICOMPRESSOR' -v -o '$dst' '$src' 2>&1 | $YUIFILTER");

open(MJX,"<", $dst);
@lines = <MJX>;
close(MJX);
$compressed = join("",@lines);

$template = "$bindir/template.js";
$template = "$bindir/template-MathJax.js" if $dst =~ m!(^|/)MathJax\.js$!;

open(MJX,"<",$template);
@lines = <MJX>;
close(MJX);
$lines = join("",@lines);

$dstname = $dst; $dstname =~ s!.*/(dpvc-)?MathJax!/MathJax!;
$lines =~ s/%%%NAME%%%/$dstname/;
$lines =~ s/%%%DATA%%%/$compressed/;


open(MJX,">",$dst);
print MJX $lines;
close(MJX);

1;

