#! /usr/bin/perl

# used internally to filter the yuicompressor output to not show certain messages

while ($line = <>) {
  if ($line =~ m/use a single 'var' statement per scope/) {
    $line = <>; $line = <>; # skip next two lines
  } elsif ($line =~ m/The symbol (VERSION|TEXCLASS|MO) is declared but/) {
    $line = <>; $line = <>; # skip next two lines
  } elsif ($line =~ m/Using 'eval' is not recommended/) {
    $line = <>; $line = <>; # skip next two lines
  } elsif ($line =~ m/Using charset (MacRoman|UTF)/) {
    $line = <>; # skip blank line
  } else {
    print $line;
  }
}

1;
