#! /usr/bin/perl

#  Creates the fontdata.js file from the individual font data files
#  
#  Usage:  ./makeData

@files = (
  "STIXGeneral-Regular",
  "STIXGeneral-Bold",
  "STIXGeneral-Italic",
  "STIXIntegralsD-Regular",
  "STIXNonUnicode-Regular",
  "STIXNonUnicode-Bold",
  "STIXNonUnicode-Italic",
  "STIXSizeOneSym-Regular",
  "STIXSizeTwoSym-Regular",
  "STIXSizeThreeSym-Regular",
  "STIXSizeFourSym-Regular",
  "STIXSizeFiveSym-Regular",
  "STIXVariants-Regular",
);

foreach $file (@files) {
  (my $name = $file) =~ s{\.[^.]+$}{};
  $file =~ s/STIX//;
  $file .= "-Regular" unless $file =~ m/-/;
  $file = "fonts/STIX/$file"; $file =~ s!-!/!g;
  $file .= (-e "$file/Main.js" ? "/Main.js" : "/All.js");
  open(FONT,$file) || print "Can't open $file\n";
  $lines = join("",<FONT>);
  close(FONT);
  $lines =~ s/.*FONTDATA/HTMLCSS.FONTDATA/s;
  $lines =~ s/};.*/};\n/s;
  print "Generating $name.js...\n";
  open(DATA,">data/$name.js");
  print DATA $lines;
  close(DATA);
}
