#! /bin/bash
# Version: Apache License 2.0
#
# Copyright (c) 2013 MathJax Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source ../../../custom.cfg

FONTDATA=$MATHJAXDIR/unpacked/jax/output/HTML-CSS/fonts/TeX/fontdata.js

for file in `cd data; ls *.js | $SED 's|\(.*\)\.js|\1|'`
do
    echo "Copying $file.js..."
    name=`$GREP HTMLCSS.FONTDATA.FONTS data/$file.js | $SED "s|.*\['\(.*\)'\].*|\1|"`
    $SED -i "/\['$name'\]/i INSERT_HERE" $FONTDATA
    $SED -i "/\['$name'\]/,/};/ {d}" $FONTDATA
    $SED -i "/INSERT_HERE/{
r data/$file.js
d
}" $FONTDATA
done
