#! /bin/csh -f

#  Creates .afm files from the MathJax .svg fonts
#  
#  Usage:  ./makeAFM

foreach file (svg/*.svg)
  echo ""
  echo $file:t
  fontforge -lang=ff -c 'Open("'$file'");Generate("afm/'$file:t:r'.afm")'
end
