#! /usr/bin/perl

#  Creates the fontdata.js file from the individual font data files
#
#  Usage:  ./makeData

opendir(AFM,"afm");
@files = grep {/.*\.afm/} (readdir(AFM));
closedir(AFM);

foreach $file (@files) {
  (my $name = $file) =~ s{\.[^.]+$}{};
  $file =~ s/\.afm//; $file =~ s/MathJax_//;
  $file .= "-Regular" unless $file =~ m/-/;
  next if $file =~ /Main-Bold|Main-Italic|Size/;
  next if $file =~ /Math-Regular|-BoldItalic|AMS|Caligraphic/;
  next if $file =~ /Fraktur|SansSerif|Script|Typewriter|WinIE/;
  $file = "fonts/TeX/svg/$file"; $file =~ s!-!/!g;
  $file .= (-e "$file/Main.js" ? "/Main.js" : "/All.js");
  open(FONT,$file) || print "Can't open $file\n";
  $lines = join("",<FONT>);
  close(FONT);
  $lines =~ s/.*FONTDATA/SVG.FONTDATA/s;
  $lines =~ s/};.*/};/s;
  print "Generating $name.js...\n";
  open(DATA,">data/$name.js");
  print DATA $lines,"\n";
  close(DATA);
}
